### ISSUE TITLE
DreamBoard bugs on iOS 7

### ISSUE THREAD

**Issue by thefinga** [wyndwarrior/DreamBoard#2]
The bugs I've noticed so far on iOS 7 with iPhone 5 and iPad 3:
- launching apps through bundleIDs have a large delay (appicons and appgrids). 
- icon labels not lining up correctly/custom icon sizes with mask/overlays not being created correctly. 
- entering and exiting edit mode has a large delay
- preview pics on the theme switcher screen don't show up
- preparing the theme takes a long time (too long)
- the _Library/Cache/Icons folder is not being created

**Comment by KCSAURAV** [comment]
It's not working in ios 7.1.multitasking shows default screen and some setup n unwanted icons show up. Is it updated from 2.0.3?

**Comment by wyndwarrior** [comment]
Don't happen to have any 7.1 devices, but feel free to submit a pull request
